# Generated by Django 5.2.8 on 2025-11-17 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('validation_errors', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_file_path', models.CharField(max_length=255)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('data_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_management.dataupload')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resulting_model', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model_management.modelversion')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('label', models.IntegerField()),
                ('subreddit', models.CharField(blank=True, max_length=100)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('features', models.JSONField(default=dict)),
                ('dataset_type', models.CharField(choices=[('train', 'Training'), ('test', 'Test'), ('unlabeled', 'Unlabeled')], default='unlabeled', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('data_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='model_management.dataupload')),
            ],
            options={
                'indexes': [models.Index(fields=['data_upload', 'is_active'], name='model_manag_data_up_ba6b06_idx'), models.Index(fields=['label'], name='model_manag_label_e60f2b_idx')],
            },
        ),
    ]
