# Generated by Django 5.2.8 on 2025-12-08 17:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('validation_errors', models.TextField(blank=True, null=True)),
                ('pipeline_type', models.CharField(choices=[('full', 'Full'), ('partial', 'Partial'), ('raw', 'Raw')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('logistic_regression', 'Logistic Regression'), ('random_forest', 'Random Forest'), ('lstm', 'LSTM'), ('transformer', 'Transformer')], max_length=30)),
                ('version_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_file_path', models.CharField(max_length=255)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('roc_plot_base64', models.TextField(blank=True, null=True)),
                ('confusion_matrix_base64', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_iter', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('regularization_strength', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('solver', models.CharField(blank=True, choices=[('lbfgs', 'lbfgs'), ('liblinear', 'liblinear'), ('newton-cg', 'newton-cg'), ('newton-cholesky', 'newton-cholesky'), ('sag', 'sag'), ('saga', 'saga')], max_length=20, null=True)),
                ('n_estimators', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_depth', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('min_samples_split', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2)])),
                ('min_samples_leaf', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('rf_max_features', models.CharField(blank=True, choices=[('sqrt', 'sqrt'), ('log2', 'log2'), ('None', 'None')], max_length=20, null=True)),
                ('n_jobs', models.IntegerField(blank=True, null=True)),
                ('ngram_range_min', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('ngram_range_max', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('min_df', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_df', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('tfidf_max_features', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('embed_dim', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('hidden_dim', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('d_model', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('n_head', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('dim_feedforward', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('num_layers', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('dropout', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('max_seq_length', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('vocab_size', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('learning_rate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('batch_size', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('epochs', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('model_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parameter', to='ml_admin.modelversion')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('logistic_regression', 'Logistic Regression'), ('random_forest', 'Random Forest'), ('lstm', 'LSTM'), ('transformer', 'Transformer')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_log', models.TextField(blank=True, null=True)),
                ('current_epoch', models.IntegerField(blank=True, null=True)),
                ('total_epochs', models.IntegerField(blank=True, null=True)),
                ('data_uploads', models.ManyToManyField(related_name='training_jobs', to='ml_admin.dataupload')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resulting_model', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ml_admin.modelversion')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('label', models.CharField(max_length=50)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('normal', models.IntegerField(default=0)),
                ('depression', models.IntegerField(default=0)),
                ('suicidal', models.IntegerField(default=0)),
                ('stress', models.IntegerField(default=0)),
                ('dataset_type', models.CharField(choices=[('train', 'Training'), ('test', 'Test'), ('increment', 'Increment')], default='train', max_length=10)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('data_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ml_admin.dataupload')),
            ],
            options={
                'indexes': [models.Index(fields=['category_id'], name='ml_admin_da_categor_11b286_idx'), models.Index(fields=['data_upload'], name='ml_admin_da_data_up_47eb58_idx'), models.Index(fields=['label'], name='ml_admin_da_label_0bd4f5_idx')],
            },
        ),
    ]
