# Generated by Django 5.2.8 on 2025-12-05 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('validation_errors', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('logistic_regression', 'Logistic Regression'), ('random_forest', 'Random Forest'), ('lstm', 'LSTM'), ('transformer', 'Transformer')], max_length=30)),
                ('version_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_file_path', models.CharField(max_length=255)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('roc_plot_base64', models.TextField(blank=True, null=True)),
                ('confusion_matrix_base64', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('logistic_regression', 'Logistic Regression'), ('random_forest', 'Random Forest'), ('lstm', 'LSTM'), ('transformer', 'Transformer')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resulting_model', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ml_admin.modelversion')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('label', models.CharField(max_length=50)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('normal', models.IntegerField(default=0)),
                ('depression', models.IntegerField(default=0)),
                ('suicidal', models.IntegerField(default=0)),
                ('stress', models.IntegerField(default=0)),
                ('dataset_type', models.CharField(choices=[('train', 'Training'), ('test', 'Test'), ('increment', 'Increment')], default='train', max_length=10)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('data_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ml_admin.dataupload')),
            ],
            options={
                'indexes': [models.Index(fields=['category_id'], name='ml_admin_da_categor_11b286_idx'), models.Index(fields=['data_upload'], name='ml_admin_da_data_up_47eb58_idx'), models.Index(fields=['label'], name='ml_admin_da_label_0bd4f5_idx')],
            },
        ),
    ]
