# Generated by Django 5.2.7 on 2025-11-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='datasetrecord',
            new_name='ml_admin_da_categor_11b286_idx',
            old_name='model_manag_categor_c8533f_idx',
        ),
        migrations.RenameIndex(
            model_name='datasetrecord',
            new_name='ml_admin_da_data_up_47eb58_idx',
            old_name='model_manag_data_up_a4f50e_idx',
        ),
        migrations.RenameIndex(
            model_name='datasetrecord',
            new_name='ml_admin_da_label_0bd4f5_idx',
            old_name='model_manag_label_e60f2b_idx',
        ),
        migrations.RemoveField(
            model_name='datasetrecord',
            name='anxiety',
        ),
        migrations.RemoveField(
            model_name='datasetrecord',
            name='bipolar',
        ),
    ]
