# Generated by Django 5.2.7 on 2025-12-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataupload',
            name='pipeline_type',
            field=models.CharField(choices=[('full', 'Full'), ('partial', 'Partial'), ('raw', 'Raw')], default='full', max_length=20),
        ),
    ]
