# Generated by Django 5.2.7 on 2025-11-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_admin', '0002_rename_model_manag_categor_c8533f_idx_ml_admin_da_categor_11b286_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
