# Generated by Django 5.2.8 on 2025-12-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_admin', '0002_alter_trainingjob_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingjob',
            old_name='error_message',
            new_name='progress_log',
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='current_epoch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='total_epochs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
