# Generated by Django 5.2.8 on 2025-11-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_admin', '0003_dataupload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='confusion_matrix_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='roc_plot_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetrecord',
            name='dataset_type',
            field=models.CharField(choices=[('train', 'Training'), ('test', 'Test'), ('increment', 'Increment')], default='train', max_length=10),
        ),
    ]
