# Generated by Django 5.2.8 on 2025-12-04 11:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_admin', '0004_modelversion_confusion_matrix_base64_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingjob',
            name='data_upload',
        ),
        migrations.AddField(
            model_name='modelversion',
            name='model_type',
            field=models.CharField(choices=[('logistic_regression', 'Logistic Regression'), ('random_forest', 'Random Forest'), ('lstm', 'LSTM'), ('transformer', 'Transformer')], default='transformer', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='model_type',
            field=models.CharField(choices=[('logistic_regression', 'Logistic Regression'), ('random_forest', 'Random Forest'), ('lstm', 'LSTM'), ('transformer', 'Transformer')], default='transformer', max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_iter', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('regularization_strength', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('solver', models.CharField(blank=True, choices=[('lbfgs', 'lbfgs'), ('liblinear', 'liblinear'), ('newton-cg', 'newton-cg'), ('newton-cholesky', 'newton-cholesky'), ('sag', 'sag'), ('saga', 'saga')], max_length=20, null=True)),
                ('n_estimators', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_depth', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('min_samples_split', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2)])),
                ('min_samples_leaf', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('rf_max_features', models.CharField(blank=True, choices=[('sqrt', 'sqrt'), ('log2', 'log2'), ('None', 'None')], max_length=20, null=True)),
                ('n_jobs', models.IntegerField(blank=True, null=True)),
                ('ngram_range_min', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('ngram_range_max', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('min_df', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_df', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('tfidf_max_features', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('embed_dim', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('hidden_dim', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('d_model', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('n_head', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('dim_feedforward', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('num_layers', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('dropout', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('max_seq_length', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('vocab_size', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('learning_rate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('batch_size', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('epochs', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('model_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='ml_admin.modelversion')),
            ],
        ),
    ]
