# Generated by Django 5.2.7 on 2025-12-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_admin', '0004_modelversion_confusion_matrix_base64_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingjob',
            name='data_upload',
        ),
        migrations.AddField(
            model_name='modelversion',
            name='model_type',
            field=models.CharField(choices=[('logistic_regression', 'Logistic Regression'), ('random_forest', 'Random Forest'), ('lstm', 'LSTM'), ('transformer', 'Transformer')], default='algotirhm', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='model_type',
            field=models.CharField(choices=[('logistic_regression', 'Logistic Regression'), ('random_forest', 'Random Forest'), ('lstm', 'LSTM'), ('transformer', 'Transformer')], default='algorithm', max_length=30),
            preserve_default=False,
        ),
    ]
