# Generated by Django 5.2.8 on 2025-12-04 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_admin', '0005_remove_trainingjob_data_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingjob',
            name='data_uploads',
            field=models.ManyToManyField(related_name='training_jobs', to='ml_admin.dataupload'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='model_version',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parameter', to='ml_admin.modelversion'),
        ),
    ]
