# Generated by Django 5.2.8 on 2025-12-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserConsent',
        ),
    ]
